### ISSUE TITLE
Add line markers for #56

### ISSUE THREAD

**Issue by prudhvije** [Imaginea/KodeBeagle#104]
Current Highlighting:
![image](https://cloud.githubusercontent.com/assets/8348624/7700242/e9bd3798-fe3a-11e4-8f18-8516fbb2017f.png)

What we want to achieve is: 
Some markers on the right side of main editor so that user can traverse easily(directly) by clicking on them.

![image](https://cloud.githubusercontent.com/assets/8348624/7700268/1b4879bc-fe3b-11e4-8a84-8867179ec3f9.png)

**Comment by ScrapCodes** [comment]
Can you explain this better ?
