### ISSUE TITLE
TinyEditors' Jpanel not showing project name and score while resizing tiny editors.

### ISSUE THREAD

**Issue by amit-shar** [Imaginea/KodeBeagle#171]
Snapshot 
![screenshot from 2015-06-01 14 52 22](https://cloud.githubusercontent.com/assets/11629465/7909949/196b8afc-086e-11e5-9184-bcfea0dd3fd1.png)

**Comment by prudhvije** [comment]
This is fixed in #172 
![image](https://cloud.githubusercontent.com/assets/8348624/8227679/e6522be2-15c6-11e5-83b9-1d09693ce146.png)

**Comment by prudhvije** [comment]
@ScrapCodes  can we close this?
