### ISSUE TITLE
Rename BetterDocs to KodeBeagle

### ISSUE THREAD

**Issue by prudhvije** [Imaginea/KodeBeagle#196]
This includes renaming packages, help, information messages, display names in plugin main window, settings etc.

**Comment by hashd** [comment]
Did you mean CodeBeagle?

**Comment by prudhvije** [comment]
I remember that "C" has been converted to "K" because of domain issues. Anyhow will check it again. Thanks for pointing out.

**Comment by hashd** [comment]
Yep, found http://sourceforge.net/projects/codebeagle/ 

Karry on with Kodebeagle
