### ISSUE TITLE
UI alignment issues

### ISSUE THREAD

**Issue by sans-sense** [Imaginea/KodeBeagle#214]
![contenteverywhere](https://cloud.githubusercontent.com/assets/542896/8255190/b73ae04c-16bb-11e5-84b6-600ae069440e.png)
As the editor widget can have varying height, the whole screen goes out of alignment in some settings

**Comment by uidev547** [comment]
as per suggestion from Dominic, new commit made to remove the listView and gridView (by default only listview will be present).
updated UI can verify http://uidev547.github.io/BetterDocs/demov1.html#?searchTerms=FileChannel
Thanks
Kiran

**Comment by uidev547** [comment]
@ScrapCodes: Please close this issue.

**Comment by hashd** [comment]
Layout has changed significantly, this issue doesn't apply anymore
