### ISSUE TITLE
UI:: Search: Web UI showing incorrect error.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#219]
![screenshot from 2015-06-24 10 37 45](https://cloud.githubusercontent.com/assets/992952/8323069/31685d28-1a5d-11e5-93c5-4afafc7c9016.png)

Actual error from server was:
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by uidev547** [comment]
please test this with error scenario... need suggestions on the implementation of this.
