### ISSUE TITLE
UI:: Search: Clicking a filename twice on left, leads to adding the code editor twice on the right panel.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#226]
![screenshot from 2015-06-25 11 25 59](https://cloud.githubusercontent.com/assets/992952/8348140/20ec762a-1b2d-11e5-86ba-e467fa010b58.png)

**Comment by uidev547** [comment]
code commited to fix this issue. 
can be verified http://uidev547.github.io/BetterDocs/demov1.html#?searchTerms=FileChannel

**Comment by ScrapCodes** [comment]
Alright sounds good. !

**Comment by hashd** [comment]
Marking as invalid as the layout has changed significantly and this is not the case anymore.
