### ISSUE TITLE
UI:: Home/Search: Auto focus on searchbox on homepage

### ISSUE THREAD

**Issue by hashd** [Imaginea/KodeBeagle#229]
User should be able to start typing as soon as he visits the homepage

**Comment by hashd** [comment]
I have implemented in my fork, http://hashd.github.com/KodeBeagle

**Comment by ScrapCodes** [comment]
You can use the label web-ui.

**Comment by uidev547** [comment]
implemented search page aswell

**Comment by hashd** [comment]
This change has been merged into gh-pages branch
