### ISSUE TITLE
UI:: Search: Use normal <code> block instead of ace editor for code snippets in results page

### ISSUE THREAD

**Issue by hashd** [Imaginea/KodeBeagle#234]

**Comment by uidev547** [comment]
can be verified at http://uidev547.github.io/BetterDocs/

**Comment by hashd** [comment]
@uidev547 Can you make the fonts consistent in snippet and ace editor

**Comment by hashd** [comment]
@uidev547 The font in fullscreen mode is set to be  Consolas while in the list mode is Monaco/Menlo

**Comment by uidev547** [comment]
this is fixed in http://uidev547.github.io/BetterDocs/search/#?searchTerms=fileChannel please check this

**Comment by hashd** [comment]
I'll raise another issue then wrt the font-family

**Comment by hashd** [comment]
This change has been merged into gh-pages branch
