### ISSUE TITLE
UI:: Search: Settings/Cogs icon and functionality should be made available only when url query has advanced=true

### ISSUE THREAD

**Issue by hashd** [Imaginea/KodeBeagle#235]

**Comment by uidev547** [comment]
can be verified at http://uidev547.github.io/BetterDocs/

**Comment by hashd** [comment]
This change has been merged into gh-pages branch.

@uidev547 Not a dealbreaker, but the cogs icon doesn't seem to be vertically aligned at the center

**Comment by uidev547** [comment]
verify this http://uidev547.github.io/BetterDocs/search/#?advanced=true

Thanks
Kiran

**Comment by hashd** [comment]
Looks good to me, nice work!
