### ISSUE TITLE
UI:: Search: Header behaviour changes

### ISSUE THREAD

**Issue by hashd** [Imaginea/KodeBeagle#238]
Instead of a fixed header, we need to target a header which pops from the top whenever the user is trying to scroll up.

**Comment by hashd** [comment]
@uidev547 Can you make it slide down rather than just pop up abruptly

**Comment by uidev547** [comment]
this can be tested http://uidev547.github.io/BetterDocs/search/

**Comment by hashd** [comment]
Cool work on this! We can close this issue after the changes are merged to gh-pages

**Comment by uidev547** [comment]
@hashd : Please check this. I think this is is fixed (http://imaginea.github.io/KodeBeagle/search/#?searchTerms=fileChannel)

**Comment by hashd** [comment]
Fixed in gh-pages branch
