### ISSUE TITLE
UI:: Search: Quick access to search field from anywhere on this page

### ISSUE THREAD

**Issue by hashd** [Imaginea/KodeBeagle#239]
As soon as the user starts typing any of 'a-zA-Z' characters, the header needs to slide down from top and the focus should be set on the search bar.

This will let the user to interact with KodeBeagle in a very easy manner.

**Comment by uidev547** [comment]
can be verified at http://uidev547.github.io/BetterDocs/

**Comment by hashd** [comment]
This change has been merged into gh-pages branch
