### ISSUE TITLE
Issue scrolling - Featured

### ISSUE THREAD

**Issue by minidoc** [Imaginea/KodeBeagle#253]
There seems to be issue with the scroll. I am able to scroll within the results only when the mouse cursor is in the area highlighted by the blue dashed line(screenshot below)

*Note - I am trying IDE on Mac OS.*

![screen shot 2015-07-06 at 13 02 38](https://cloud.githubusercontent.com/assets/1484393/8519376/fd5bb920-23ef-11e5-8874-31cf3cb31593.png)

**Comment by ScrapCodes** [comment]
This is difficult to solve. And it becomes more evident in MAC. In Linux the inner scroll of tiny editors are visible so it gives somewhat intuition to users that they can not scroll there.
