### ISSUE TITLE
Positioning sub-sections inside "All" section

### ISSUE THREAD

**Issue by minidoc** [Imaginea/KodeBeagle#254]
1. Can we switch these two panes? (screenshot below)
* The collapse and expand buttons on top act only on results coming at the bottom.
* The UI movement should, as much as possible, be from top to bottom. In this case the user will need to act from bottom to top. 

![screen shot 2015-07-06 at 13 03 12](https://cloud.githubusercontent.com/assets/1484393/8519529/f4f545b6-23f0-11e5-965a-7cd2a999caca.png)

**Comment by ScrapCodes** [comment]
This seems to be fixed. Not sure how we lost the PR targetting this issue
