### ISSUE TITLE
UI:: General: Footer for KodeBeagle web UI.

### ISSUE THREAD

**Issue by prudhvije** [Imaginea/KodeBeagle#303]
It would be great to have one footer for copyright information and some other stuff.

**Comment by uidev547** [comment]
this can be verified in http://uidev547.github.io/BetterDocs/ all pages

**Comment by hashd** [comment]
Cool work on this! We can close this issue after the changes are merged to gh-pages

Eventually we can have a more elaborate footer with more links to stuff.
