### ISSUE TITLE
Sorting of results and methods section on the web ui.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#311]
For sorting results section, we can use number of methods against each import. And break ties based on number of search occurrences. 

For methods section, sort on number of occurrences of imports.

**Comment by sachintyagi22** [comment]
We are currently sorting the files based on the stars of its containing repository. It is debatable that changing that sorting criteria with imports count in a file will lead to any better result. So let's keep the results section as is. 

But sorting methods in method section by their occurrence count makes sense. @venkateshragi please look into this.
