### ISSUE TITLE
[Discuss] Make a milestone release for web UI as well and follow the process we do for core and plugin.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#333]
My impression is such that, we do separate release for core, idea plugin and web ui. Somehow the core is so insignificant, that it can gel well with idea plugin. 

But I guess UI is equally significant piece and needs its own release cycle milestone etc..  Please do not send all at once PR !

This also the reason UI dev were left out from Release credits for idea plugin. Because there is separate release for them. We need to sort this out in the sense shall we make UI and core release cycle coincide ? and if so how ? 

@minidoc

**Comment by minidoc** [comment]
@hashd already seems to have defined the milestone for web-UI. 

Could you drive this forward for the web-UI @hashd? It would be good to define the release cycle and associate tickets with them.

**Comment by ScrapCodes** [comment]
So this was discussed with folks and will be discussed more on forums.
