### ISSUE TITLE
If two different project have same filename in result sets for a search wrong/junk results are displayed.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#334]
![screenshot from 2015-08-05 09 51 16](https://cloud.githubusercontent.com/assets/992952/9078159/8d3a3d18-3b57-11e5-87ce-84dfd150b5bd.png)

**Comment by prudhvije** [comment]
I guess this can be fixed once we use caching mechanism, there we sill store complete path of file including project name, directory structure.
