### ISSUE TITLE
Fail whale for kodebeagle.com

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#342]
Something like this:
https://en.wikipedia.org/wiki/File:Failwhale.png

**Comment by uidev547** [comment]
Hi @ScrapCodes 
What is the sample response from the server, while server is down ?

Thanks
Kiran

**Comment by ScrapCodes** [comment]
Any http response greater than or equal to 500 is an indication of
something is wrong.

Prashant Sharma

**Comment by hashd** [comment]
@uidev547 feedback from @ScrapCodes was that the text could be larger and more bolder on the failwhale background. 

In its current state, the text is not easily readable.

**Comment by sachintyagi22** [comment]
We got the sinking ship image. Closing this now.
