### ISSUE TITLE
removing the duplicated code ( html /  js / css ) in the site

### ISSUE THREAD

**Issue by uidev547** [Imaginea/KodeBeagle#353]
1. create the site in component manner like header includes footer includes using Jekyll template.
2. we have search box component in in home and search page make this as one component include this in two pages ( now js for these two page created differently )
3. most of the css in repeated in all the pages so create the less files in component wise and load it iff it is required.
cc: @hashd, @ScrapCodes

**Comment by hashd** [comment]
Any estimate on effort required in terms of days?

**Comment by uidev547** [comment]
Basically this issues found out while working for #316.
so i have started working on this as well. estimation for this work alone will take 2days. As  I have already  started this work this will be done today EOD.
