### ISSUE TITLE
[web-ui] show search examples below the search bar

### ISSUE THREAD

**Issue by hashd** [Imaginea/KodeBeagle#356]
![1](https://cloud.githubusercontent.com/assets/945317/9360535/687cc8ca-46b4-11e5-9cbe-abe1367586a9.png)

**Comment by hashd** [comment]
Suggested by Rajani

**Comment by sachintyagi22** [comment]
We support only the 'Type' search for now (so do not need any DSL markup in query). The supported suggestions are now being shown below the search bar.
