### ISSUE TITLE
filtering methods or imports can be improved to next level

### ISSUE THREAD

**Issue by uidev547** [Imaginea/KodeBeagle#363]
When a filtering a method or import we are getting all the matches of the file in the result editor.
It is better if we see the only selected method matches in the result editors.  
![screenshot from 2015-08-26 17 58 10](https://cloud.githubusercontent.com/assets/6046714/9493309/4b23808a-4c1c-11e5-8a87-0c38f9a0f45f.png)

In the attached image filter is done on **force** method but still we are showing the other matches which is not expected ( expectations is it should show only **force** method matches ). 

ping: @ScrapCodes , @hashd

**Comment by hashd** [comment]
Sounds logical to me, @ScrapCodes: what do u think?

**Comment by hashd** [comment]
This has been addressed
