### ISSUE TITLE
fine tuning in the file content request from front end

### ISSUE THREAD

**Issue by uidev547** [Imaginea/KodeBeagle#366]
while doing the filtering request fetch the file content only if content is not available in the client side.
attached screenshots.
screenshot1:
![screenshot1](https://cloud.githubusercontent.com/assets/6046714/9541563/2156230e-4d87-11e5-8e39-3d906abf0a75.png)

screenshot2:
![screenshot2](https://cloud.githubusercontent.com/assets/6046714/9541564/216409ba-4d87-11e5-98ba-ae3b946804ff.png)

In the screenshot1 and screenshot2 though the showing results are same but still we could see **one more  service call** as we change the filtering.

cc: @hashd, @ScrapCodes

**Comment by sachintyagi22** [comment]
This is fixed by the new indices.
