### ISSUE TITLE
Duplication of source file in tmp directory when deleted

### ISSUE THREAD

**Issue by keerath** [Imaginea/KodeBeagle#367]
When a source file is deliberately deleted from /tmp directory ... and the same file is opened again in the plugin ... it creates two copies of it... one lies in a folder created by the digest of file's project path and other lies in the folder whose name is generated by random UUID.

**Comment by hashd** [comment]
adding labels as mentioned by Keerath as he doesn't have sufficient priviledges

**Comment by prudhvije** [comment]
@keerath Idea in duplicating the file is Idea (I mean IDEA) doesn't check again whether the file exists or not once it has been deleted and returns NPE for any operation done on that file. So, to avoid that we are creating another file under random UUID directory name. Hope this helps.  Workaround for this might be once we detected that original file in the directory is no longer being used we can delete if one can assure that the operation is safe. Hope this helps.

**Comment by keerath** [comment]
Or all we need is to refresh the file system and search for the newly created file instead of creating another one in a folder named with some random UUID

**Comment by prudhvije** [comment]
@keerath You can go ahead with that approach if it's gonna work.
