### ISSUE TITLE
[web-ui] corrections needed in advanced settings popup

### ISSUE THREAD

**Issue by hashd** [Imaginea/KodeBeagle#390]
- Fix spelling errors
- Keep casing consistent

![kb-advanced-settings-panel](https://cloud.githubusercontent.com/assets/945317/9730800/96eae43a-5636-11e5-823c-d957bba8bff2.png)

**Comment by hashd** [comment]
Change the header to *Configuration* instead of *Configuration and preview*. Looks good to me otherwise

**Comment by hashd** [comment]
Rename **Kode Beagle** to **KodeBeagle**, try to follow the same brand name

**Comment by hashd** [comment]
**Url** can be **URL**

**Comment by hashd** [comment]
@uidev547 Kindly make note of the points above

**Comment by sachintyagi22** [comment]
Fixed by #473 .
