### ISSUE TITLE
[web-ui] Highlight only method usages when user attempts to refine based on methods

### ISSUE THREAD

**Issue by hashd** [Imaginea/KodeBeagle#394]
In this image, I tried to refine results for MappedByteBuffer.force but the lines highlighted are pretty much for everything else.

![mbb-force](https://cloud.githubusercontent.com/assets/945317/9806797/4e06344e-5867-11e5-805b-59eff7c05a24.png)

**Comment by hashd** [comment]
@ScrapCodes this would be the expected behaviour right? 
@uidev547 after @ScrapCodes confirms, if  you do not have the required information, check with @PiyushMishra on the same.

**Comment by ScrapCodes** [comment]
Yes makes sense.

**Comment by uidev547** [comment]
@hashd This is duplicate of #363, is n't it?

**Comment by hashd** [comment]
Yep, it is. Closing this issue
