### ISSUE TITLE
Found this while using 0.1.3 version of plugin.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#403]
An exception occurred while processing your request:java.lang.IllegalArgumentException: Argument for @NotNull parameter 'chars' of com/intellij/openapi/editor/impl/DocumentImpl.  must not be null Ideally it should be safe to ignore. However if problem persists, please report it to us by sending an email to kodebeagle@googlegroups.com

**Comment by keerath** [comment]
@ScrapCodes could you please paste the stack trace..!!

**Comment by ScrapCodes** [comment]
There is no way I could get it :(, We should fix this too !

Prashant Sharma

**Comment by ScrapCodes** [comment]
Only possible place I think this could come is: Document tinyEditorDoc = new DocumentImpl(contents, true, false); 
Where contents is null

**Comment by keerath** [comment]
ya so before calling this we could probably check if the contents are not found in the map (or null)... then we could exclusively query for the contents of that file

**Comment by keerath** [comment]
By doing so there might be an extra overhead of another request but this bug will not occur..!!

**Comment by ScrapCodes** [comment]
@keerath Should we close this ?

**Comment by keerath** [comment]
Yes we can close this .. as we do ignore files who content is null or empty

**Comment by keerath** [comment]
@ScrapCodes this issue is already closed in this pr #422
