### ISSUE TITLE
Some changes for "Terms and conditions" and "Privacy policy page".

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#405]
While reviewing the website on imaginea.github.io/KodeBeagle and pages 
http://imaginea.github.io/KodeBeagle/about/terms-conditions.html

1) Fix the formatting of the text.
2) Change title to only say "Terms and conditions." and KodeBeagle Terms and conditions ...
3) Replace Idea Plugin with Idea Plugin or kodebeagle.com website.

Add a paragraph, KodeBeagle is an opensource software licensed with Apache 2 License. We thus encourage users to alter code and have their custom or altered deploy of kodebeagle. This terms and conditions is not applicable for such deploys. They may have their own terms and conditions.

http://imaginea.github.io/KodeBeagle/about/privacy-policy.html

1) Change the contact us to opensource@imaginea.com.

Please use the assistance of @keerath to understand further changes.

**Comment by ScrapCodes** [comment]
I edited the content, because "may be" the word "common sense" can be offending. Thank you for pointing out @hashd. Hope it aligns with the policy now. I seriously have no intentions for offending anyone. I just meant in a different context.

**Comment by hashd** [comment]
Usage of the term 'Common sense' can be taken in a offensive manner, so try avoiding using it hereafter atleast in a public space like Github.

Its nice to see the community taking their Code of Conduct seriously :+1:

**Comment by hashd** [comment]
Looks good to me.

PTAL @keerath and let @uidev547 know if any further changes need to be done.
