### ISSUE TITLE
Limit the number of keyword for the search.

### ISSUE THREAD

**Issue by ScrapCodes** [Imaginea/KodeBeagle#430]
Good Ux is important here.

Large number of keywords often lead to "no results at all" and in most cases some of the keywords are not even intended to be searched. So to restrict, we can allow user to edit the number of keywords by disabling the search button(if the number of keywords are more than 6) and giving a text saying that he needs to make less than SIX keywords before he can search.

Something like:
"Please narrow you search, only Six keywords are allowed. This helps in bringing out more relevant results and leads to less complex system."

**Comment by Shiti** [comment]
Maybe you can give users the option where they select it to be an `and` / `or`

**Comment by venkoux** [comment]
@sachintyagi22 
Hi, I am working on this task can you please assign it to me.

Thanks.

**Comment by hashd** [comment]
@venkoux Thanks for taking this up. I think you can go ahead and create a PR once you are done with the changes.

**Comment by MohitSuhane** [comment]
@hashd 
Hi ,
Mohit here.
Sry for spam, the above comment was not done by Venu.  
Venu was giving me some KT and by mistake I pinged with his account.
I am taking up this task and will create a PR once done.

Thanks.

**Comment by sachintyagi22** [comment]
This case is no longer valid. We are not doing must.
