### ISSUE TITLE
Chrome Plugin does not work

### ISSUE THREAD

**Issue by Shiti** [Imaginea/KodeBeagle#431]
Chrome Version 46.0.2490.64 beta (64-bit)
OS Fedora 22

**Comment by hashd** [comment]
Can you also provide information on the mode of installation and nature of the bug? 

- If you're not getting the **Search this selection on KodeBeagle.** option in the context menu then it could be a installation error.
- If you're getting the option but nothing happens after you click that menu option then it is most likely to be a bug in the plugin.

**Comment by Shiti** [comment]
I am not getting the Search this selection on KodeBeagle. option in the context menu then it could be a installation error

**Comment by Shiti** [comment]
Are there any logs which I can provide to debug that?

**Comment by hashd** [comment]
Yes, you could head to `chrome://extensions/` and hit the link **background page** link under the KodeBeagle extension section. You can look at the console for any errors.

Anyways where did you install it from? If you're getting the error on the Chrome store then we'll have to look into it carefully.

**Comment by Shiti** [comment]
I did it from chrome store only

**Comment by Shiti** [comment]
I didn't understand how to look at the error/logs

**Comment by hashd** [comment]
Click on background page as in the image below. You'll be greeted to a familiar Chrome console which can have some error information captured.

![kodebeagle-chrome-extension](https://cloud.githubusercontent.com/assets/945317/10690995/49506f48-79a3-11e5-8de6-04e04279c499.png)

**Comment by hashd** [comment]
**Search this selection on KodeBeagle.** will appear in the context menu only on selections, just in case you misunderstood my comment earlier

**Comment by Shiti** [comment]
Actually I dont have that option
![screenshot from 2015-10-23 16-44-47](https://cloud.githubusercontent.com/assets/930312/10691250/69343716-79a5-11e5-8167-2a02227e40f9.png)

**Comment by keerath** [comment]
Toggle the developer mode option in the extension page on the top right corner

**Comment by Shiti** [comment]
sorry didnt notice that. but after I did that too I have an empty console

**Comment by hashd** [comment]
Installation went fine and the plugin loads without any error.

Just to be sure, have you tried selecting some text and then tried to access the context menu on the selection or are you just searching for the option on the right click context menu under normal circumstances?

**Comment by Shiti** [comment]
I logged off and then logged in an it seems to work now

**Comment by hashd** [comment]
That's strange, can you try reproducing the original issue if possible.

**Comment by Shiti** [comment]
Tried uninstalling and installing a couple of times but could not replicate.
