### ISSUE TITLE
Support building a fat spark jar to be run on cluster

### ISSUE THREAD

**Issue by sachintyagi22** [Imaginea/KodeBeagle#542]
[While also allowing the to run Kodebeagle in local mode through sbt on Spark.]

**Comment by keerath** [comment]
Take a look at http://stackoverflow.com/questions/18838944/how-to-add-provided-dependencies-back-to-run-test-tasks-classpath/21803413#21803413

**Comment by sachintyagi22** [comment]
Done by creating a separate task. If one needs to build an assembly, need to go to 'project fatJar' in sbt shell and then invoke assembly. Core will continue to have default behaviour as now.
