### ISSUE TITLE
Java Parser Issue for external ref list 

### ISSUE THREAD

**Issue by dasbipulkumar** [Imaginea/KodeBeagle#561]
"{"id":7,"fqt":"**? extends** java.util.zip.ZipEntry"}"
{"id":11,"fqt":"java.lang.InterruptedException **|** android.os.RemoteException"}

**Comment by dasbipulkumar** [comment]
{"typeName":** ""**, 
{"typeName":"com.zumisoft.rack.RubyStringIO.createStringIOClass(runtime)

**Comment by sachintyagi22** [comment]
provide more information -- which index/method is this coming in? How can it be reproduced?

**Comment by dasbipulkumar** [comment]
for "" typeName

{"repoId":1904,"file":"dustin/java-memcached-client/blob/master/src/test/java/net/spy/memcached/ProtocolBaseCase.java","types":[{"typeName":"net.spy.memcached.client","lines":[{"lineNumber":788,"startColumn":11,"endColumn":19},{"lineNumber":790,"startColumn":24,"endColumn":27}],"properties":[{"propertyName":"shutdown","lines":[{"lineNumber":788,"startColumn":11,"endColumn":19}]},{"propertyName":"get","lines":[{"lineNumber":790,"startColumn":24,"endColumn":27}]}]},{"typeName":"","lines":[{"lineNumber":791,"startColumn":6,"endColumn":10},{"lineNumber":795,"startColumn":6,"endColumn":16}],"properties":[{"propertyName":"initClient","lines":[{"lineNumber":795,"startColumn":6,"endColumn":16}]},{"propertyName":"fail","lines":[{"lineNumber":791,"startColumn":6,"endColumn":10}]}]}],"score":423}

**Comment by dasbipulkumar** [comment]
(new java.lang.Thread(this),start,simonpk/fireeagle-updater-midlet/blob/master/src/FEMidlet.java,2531)
(m.getUnderlyingDigest(),getAlgorithmName,simonpk/j2me-oauth/blob/master/src/net/oauth/j2me/signature/HMACSHA1Signature.java,2490)
(net.oauth.j2me.Integer.toHexString((int)c),toUpperCase,simonpk/j2me-oauth/blob/master/src/net/oauth/j2me/Util.java,2490)
(java.util.List<java.net.URL>,size,dustin/java-memcached-client/blob/master/src/main/java/net/spy/memcached/AddrUtil.java,1904)
(b.setDaemon(true).setShouldOptimize(false).setFailureMode(FailureMode.Redistribute).setHashAlg(DefaultHashAlgorithm.KETAMA_HASH).setInitialObservers(Collections.singleton(testObserver)).setOpFact(new BinaryOperationFactory()).setOpTimeout(4225).setOpQueueFactory(opQueueFactory).setReadOpQueueFactory(rQueueFactory).setWriteOpQueueFactory(wQueueFactory).setReadBufferSize(19).setTranscoder(new WhalinTranscoder()),setUseNagleAlgorithm,dustin/java-memcached-client/blob/master/src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java,1904)
(b.setDaemon(true).setShouldOptimize(false).setFailureMode(FailureMode.Redistribute).setHashAlg(DefaultHashAlgorithm.KETAMA_HASH).setInitialObservers(Collections.singleton(testObserver)),setOpFact,dustin/java-memcached-client/blob/master/src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java,1904)
(b.setDaemon(true).setShouldOptimize(false),setFailureMode,dustin/java-memcached-client/blob/master/src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java,1904)
(b.setDaemon(true).setShouldOptimize(false).setFailureMode(FailureMode.Redistribute).setHashAlg(DefaultHashAlgorithm.KETAMA_HASH).setInitialObservers(Collections.singleton(testObserver)).setOpFact(new BinaryOperationFactory()).setOpTimeout(4225).setOpQueueFactory(opQueueFactory).setReadOpQueueFactory(rQueueFactory).setWriteOpQueueFactory(wQueueFactory),setReadBufferSize,dustin/java-memcached-client/blob/master/src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java,1904)
(java.util.concurrent.LinkedBlockingQueue<net.spy.memcached.ops.Operation>,LinkedBlockingQueue<Operation>,dustin/java-memcached-client/blob/master/src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java,1904)
(f.getInitialObservers(),size,dustin/java-memcached-client/blob/master/src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java,1904)
(f.getInitialObservers(),iterator,dustin/java-memcached-client/blob/master/src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java,1904)
(b.setDaemon(true),setShouldOptimize,dustin/java-memcached-client/blob/master/src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java,1904)

**Comment by sachintyagi22** [comment]
No, this doesn't help. You have to put the exact problem in parser output (what output is this above?), for which file (file location) did the problem occur etc. 

Otherwise, how can anyone be sure if the problem is fixed?
