### ISSUE TITLE
Unable to view search results - UI

### ISSUE THREAD

**Issue by sharanya24** [Imaginea/KodeBeagle#565]
No records are fetched upon searching keywords in UI. But the records are found in ElasticSearch.

The Below log message is observed from elasticsearch logs

 **[Zeitgeist] low disk watermark [85%] exceeded on [A5caQGIVS8muFG9eN5Cfow][Zeitgeist][/opt/software/elasticsearch-2.3.4/data/elasticsearch/nodes/0] free: 212.4gb[11.6%], replicas will not be assigned to this node**

**Comment by sachintyagi22** [comment]
No longer valid.
