### ISSUE TITLE
No validation on search keyword

### ISSUE THREAD

**Issue by sivakumargollu** [Imaginea/KodeBeagle#566]
In kodebeagle, We search for **class or method or some types**. All these types follow certain **rules of declarations** ; like only alphnumerics allowed and symbols not allowed except few( **UNDERSCORE**). In kodebeagle search there no validation observed to verify the validity of the search key word. 

Case 1: When we enter symbols only like "**#$%**" UI is breaking.

Case 2: When we enter words like "**Java^$@**" search is results are 0 because search keyword itself is not valid

Case 3: When we enter only a character like "P" We are getting some results. But probably no valid repository would  define a "**Type**" with single character as type. say like "**P**"

Preventing search  with invalid words  in all above cases also minimize the traffic to the server.

**Comment by sharanya24** [comment]
When entered more than certain words in text field for search
1. Overlapping of search icon on text field.
2. Proper alignment of input fields should be handled.

**Comment by sachintyagi22** [comment]
We do not want to restrict user to search only certain formats of keywords. In this iteration we are allowing the user to query on free form text which will later be matched against types or methods. Validation upfront makes little sense -- if the search term is exotic, the user will simply see no result.
