### ISSUE TITLE
Undefined shows up in search bar when user selects type on the search listing page.

### ISSUE THREAD

**Issue by sachintyagi22** [Imaginea/KodeBeagle#622]
See this -- ![image](https://cloud.githubusercontent.com/assets/10532956/18168863/5ba79530-7075-11e6-984c-f8702a7857db.png)

**Comment by sudarshanch** [comment]
I tried this, but couldn't see user is selected 'undefined' using select component.
May be I think you tried here as a type word with 'undefined'

Attaching the screenshot for reference: 
![type_word_request](https://cloud.githubusercontent.com/assets/2115055/18262848/e5360c90-7422-11e6-8319-fa503308702f.png)

**Comment by sudarshanch** [comment]
I am able to reproduce this now. will push a fix.
