### ISSUE TITLE
Double clicking on the selected search text, showing as [Object Object]

### ISSUE THREAD

**Issue by sudarshanch** [Imaginea/KodeBeagle#630]
We need to display the search term to edit it for user.
![2016-09-07_1603](https://cloud.githubusercontent.com/assets/2115055/18309032/f86a4f4a-7514-11e6-87fb-e60d29c7b48a.png)

**Comment by praveenpuglia** [comment]
Is this already in the production? I see it happening there.

**Comment by sudarshanch** [comment]
@praveenpuglia  this is not yet in PROD. @keerath @sachintyagi22 can we deploy latest UI to PROD.
